
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/treading_db
    username: postgres
    password: danik22081
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  freemarker:
    expose-request-attributes: true

stripe:
  api:
    key: "stripe key"

razorpay:
  api:
    key: "razorpay api key"
    secret: "razorpay api secret"
