
spring:
  datasource:
    url: "YOUR SPRING_DATASOURCE_URL"
    username: "YOUR SPRING_DATASOURCE_NAME"
    password: "YOUR SPRING_DATASOURCE_PASSWORD"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: "YOUR SPRING_DATABASE_NAME"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  freemarker:
    expose-request-attributes: true

stripe:
  api:
    publishableKey: "pk_test_51PmLzsGpqkpFM9QplsoarZ4R1j8nybp1XnKVI8D0IDVMuXpLAbRRtW377wktxSkEZf4gjESSfrEqqBOCnVvNAIzd00cGbW7HuR"
    secretKey: "sk_test_51PmLzsGpqkpFM9Qp5ECdqIKfFZvsJnQwi7RY2XWmWSLPu17nzJ4tPnDJbM9apYtfm6lOPilYGiIpN8VbJ13EN9hx00l0CIedvO"

razorpay:
  api:
    key: "RAZOR_PUBLISHABLE_KEY"
    secret: "RAZOR_SECRET_KEY"
